name: test

on:
  pull_request:
  push:
    paths:
      - '**.el'
      - '**.yaml'
    branches:
      - main

jobs:
  test-builtin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.2
          - 28.2
          - 29.3
          - release-snapshot
          - snapshot
        ignore_warnings:
          - true

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: pg
          POSTGRES_PASSWORD: pg
          POSTGRES_USER: pg
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mariadb:
        image: mariadb:latest
        env:
          DATABASE_HOST: 127.0.0.1
          MARIADB_DATABASE: db
          MARIADB_ROOT_PASSWORD: mysql
          MARIADB_USER: maria
          MARIADB_PASSWORD: maria
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: leotaku/elisp-check@master
      with:
        check: ert
        file: ob-sql-session-tests.el
