name: test

on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  test-builtin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
          - 27.2
          - 28.2
          - 29.3
          - release-snapshot
          - snapshot
        ignore_warnings:
          - true
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        check: ert
        file: tests.el
        
